export const SCRIPT_PART1 = [
  // PART 1
  {part:1,t:"[LIVE | Stream ON]\nCHAT: W CHUG 🔥 GOAT"},
  {t:'CHUG: "Too easy."'},
  {t:'DONATION: "You play for them… Play for me."',gl:true},
  {t:'[Chat freezes]\nCHUG: "…What?"'},
  {t:'REFLECTION: "You love this."\nCHUG: "Who are you?"'},
  {t:'REFLECTION: "The part that doesn\'t need them."',gl:true},
  {t:'[Chat dragged into the screen]'},
  {t:'CHUG: "…Hello? Bro?"'},
  {t:'GUIDE: "They\'re not here. You broke the boundary."'},
  {t:'CHUG: "My stream?"\nGUIDE: "Gone. Stand without them."'},
  {t:'SYSTEM: BEST OF 3. FIGHT.',fight:1},
  {t:'[Enemy dissolves → red fragment]',col:'#ff003c'},
  {t:'CHUG: "What was that?"\nGUIDE: "A piece of you."'},
  {t:'ENEMIES: "Win… don\'t lose…"\nCHUG: "SHUT UP!"',gl:true,col:'#ff003c'},
  {t:'SYSTEM: RAGE AWAKENED. NO MERCY.',fight:2},
  {t:'CHUG: "…What was that power?"\nGUIDE: "Yours."'},
  {t:'[A massive silhouette appears]'},
  {t:'CHUG: "I\'m not done."\nSYSTEM: FINAL ECHO',fight:3},

  {t:'[EXPANDED ENCOUNTER — OPENING DESCENT]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:2},
  {t:'— END OF PART 1 —',end:true},
  // PART 2
  {part:2,t:'PART 2 — THE WATCHER',col:'#00e5ff'},
  {t:'[Same void | ash falling]\nCHUG walks forward.'},
  {t:'CHUG: "…I heard that."'},
  {t:'[Enemy appears — faster, cleaner]\nENEMY: "You taught me this."'},
  {t:'CHUG: "…What?"\nENEMY: "…That\'s my move."'},
  {t:'SYSTEM: COMBAT EVOLVED',fight:4},
  {t:'[Enemy dissolves]\nSYSTEM: SKILL FRAGMENT ACQUIRED',col:'#ff003c'},
  {t:'CHUG: "These… aren\'t random."\nGUIDE: "No. They\'re familiar."'},
  {t:'[Environment flickers]',gl:true},
  {t:'VOICE (DISTORTED): "Queue again, bro."\nCHUG: "…Bro?"'},
  {t:'[Image glitches before face reveal]',gl:true},
  {t:'CHUG: "You knew this."\nGUIDE: "…I know how this ends."'},
  {t:'CHUG: "Then say it."\nGUIDE: "You won\'t like it."'},
  {t:'[Far distance — silhouette again]'},
  {t:'CHUG: "Stop hiding."\n[Silhouette steps forward]'},
  {t:'WATCHER: "…You\'re slower."\n[Instant silence]'},
  {t:'CHUG: "…"\nWATCHER: "You lost something."'},
  {t:'CHUG: "What?"\nWATCHER: "…Someone."'},
  {t:'WATCHER (quieter):\n"…Left chair in frame the whole time."\n[Pause]\nCHUG: "…How do you know that?"'},
  {t:'WATCHER:\n"…Because I was in it."\n[Instant silence]\n[Watcher disappears]',gl:true},
  {t:'[Floating screen activates]\nChat appears corrupted.',gl:true},
  {t:'CHAT:\n"Where is he?"\n"Solo now?"\n"He got better alone tbh"'},
  {t:'CHAT (GLITCHED):\n"He didn\'t need you."',col:'#ff003c'},
  {t:'[Flash — two players side by side]\nPerfect sync.',gl:true},
  {t:'VOICE: "We\'re unstoppable."\nCHUG: "…We?"'},
  {t:'CHUG: "Who was with me?"\nGUIDE: "…You chose not to remember."'},
  {t:'[Stronger enemy — mirrors Chug]\nMINI BOSS: "I learned from you."'},
  {t:'CHUG: "…Show your face."\nMINI BOSS: "…Not yet."'},
  {t:'SYSTEM: MIRROR MATCH',fight:5},
  {t:'[Defeat]\nSYSTEM: SYNC LEVEL INCREASED',col:'#00e5ff'},
  {t:'CHUG: "To what?"\nGUIDE: "…To him."'},
  {t:'WATCHER: "You\'re starting to remember."\nCHUG: "…I never forgot."'},
  {t:'WATCHER: "…Then why did you leave me behind?"'},
  {t:'CHUG: "…I didn\'t—"\n[Watcher disappears]'},
  {t:'CHUG: "…Who are you?"'},

  {t:'[EXPANDED ENCOUNTER — THE WATCHER]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:4},
  {t:'[EXPANDED ENCOUNTER — THE WATCHER]\\nAMBUSH WAVE. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:5},
  {t:'— END OF PART 2 —',end:true},

  // PART 3
  {part:3,t:'PART 3 — ECHOES',col:'#aa00ff'},
  {t:'[Deeper void | heavier atmosphere]'},
  {t:'CHUG: "…Feels different."\nGUIDE: "You\'re closer."'},
  {t:'CHUG: "To him?"\nGUIDE: "…To truth."'},
  {t:'[Movement lags]\nCHUG: "…What?"'},
  {t:'[Enemy appears — moves perfectly smooth]\nENEMY: "You\'re behind."'},
  {t:'SYSTEM: LATENCY ENGAGED',fight:6},
  {t:'[Enemy dissolves]\nSYSTEM: LATENCY FRACTURE CLEARED'},
  {t:'GUIDE: "He relies on prediction."'},
  {t:'[Flash: Chug + dual screens]',gl:true},
  {t:'VOICE (CLEARER): "I got your back."'},
  {t:'CHUG freezes.\nCHUG: "…Say it again."'},
  {t:'[Clip glitches out]',gl:true},
  {t:'GUIDE: "It does when winning matters more than people."'},
  {t:'WATCHER: "You still move the same."\nCHUG: "…Show yourself."'},
  {t:'WATCHER: "…Too late."\n[Watcher fades]'},
  {t:'ENEMIES:\n"Force him left."\n"Punish recovery."'},
  {t:'SYSTEM: PREDICTION WINDOW UNLOCKED',fight:7},
  {t:'VOICE 1: "We go big or nothing."\nVOICE 2: "Together."'},
  {t:'CHUG (quiet): "…I said that."'},
  {t:'GUIDE: "…You win."\nCHUG: "…That\'s it?"\nGUIDE: "…And lose everything else."'},
  {t:'[Enemy — perfect mirror]\nELITE: "…Someone you replaced."'},
  {t:'SYSTEM: COMBAT MIRROR',fight:8},
  {t:'[Enemy dissolves slowly]\nSYSTEM: SYNC ++',col:'#aa00ff'},
  {t:'[Flash — two chairs. One empty.]',gl:true},
  {t:'WATCHER: "You didn\'t what?"'},
  {t:'CHUG: "…I didn\'t leave you."'},
  {t:'WATCHER: "…You just kept going."'},
  {t:'CHUG: "…Who did I leave behind?"'},
  {t:'GUIDE: "…You\'ll remember."'},

  {t:'[EXPANDED ENCOUNTER — ECHOES]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:5},
  {t:'— END OF PART 3 —',end:true},

  // PART 4
  {part:4,t:'PART 4 — LEFT BEHIND',col:'#4488aa'},
  {t:'[Deeper layer | ground cracked | heavier gravity]\nSFX: slow heartbeat'},
  {t:'CHUG: "…It\'s getting harder to breathe."\nGUIDE: "Not harder."'},
  {t:'GUIDE: "Heavier."'},
  {t:'CHUG: "…Why does everything feel heavier?"\nGUIDE: "Because you\'re carrying it now."'},
  {t:'CHUG: "…Carrying what?"\nGUIDE: "…What you ignored."'},
  {t:'[Enemy appears — slow, dragging]\nENEMY:\n"You kept going…"\n"…and never looked back…"'},
  {t:'CHUG: "Stop talking."'},
  {t:'SYSTEM: BURDEN ENGAGED',fight:9},
  {t:'SYSTEM: "BURDEN FRAGMENT ACQUIRED"'},
  {t:'CHUG: "…This place is messing with me."\nGUIDE: "No."'},
  {t:'GUIDE: "It\'s showing you."'},
  {t:'[Scene repeats itself]\n[Same path… same enemy spawn]',gl:true},
  {t:'ENEMY (REPEAT):\n"You kept going…"\nCHUG: "…This already happened."'},
  {t:'GUIDE: "Yes."\nCHUG: "…Why?"\nGUIDE: "Because you never stopped."'},
  {t:'[Audio glitch mid-air]',gl:true},
  {t:'VOICE (CLEARER NOW):\n"Bro… wait up."'},
  {t:'VOICE:\n"…You\'re going too fast."\n\nCHUG freezes.'},
  {t:'CHUG:\n"…I know that voice."'},
  {t:'[Watcher appears closer than ever]\nStill no face. Silhouette.'},
  {t:'WATCHER:\n"You heard it."\nCHUG: "…Who are you?"'},
  {t:'WATCHER:\n"…Say it."\nCHUG: "I don\'t know."'},
  {t:'WATCHER:\n"…Exactly."'},
  {t:'[Watcher starts walking away slowly]'},
  {t:'CHUG:\n"WAIT."'},
  {t:'WATCHER:\n"You didn\'t wait for me."'},
  {t:'CHUG:\n"…I didn\'t—"\n[Watcher disappears]',col:'#ff003c'},
  {t:'[Enemies attack in patterns]\nENEMIES:\n"Punish him."\n"Don\'t let him recover."'},
  {t:'SYSTEM: STAMINA SYSTEM ACTIVE'},
  {t:'CHUG:\n"…This isn\'t fair."\nGUIDE:\n"…It never was."'},
  {t:'SYSTEM: ELITE PATTERN',fight:10},
  {t:'[Chug overwhelmed briefly]\n[Falls to knee]'},
  {t:'FLASH:\nTwo players running together\n\nVOICE:\n"Don\'t leave me behind."',gl:true},
  {t:'CHUG:\n"…I didn\'t leave anyone."'},
  {t:'GUIDE:\n"…Then why does he keep saying it?"'},
  {t:'CHUG:\n"…Because you\'re lying."\nGUIDE:\n"…Or because you are."'},
  {t:'[No enemies for a while]\n[Just footsteps + breathing]'},
  {t:'CHAT (FAINT):\n"Solo now?"\n"He upgraded"\n"Other guy was holding him back anyway"',col:'#ff003c'},
  {t:'CHUG clenches fist.'},
  {t:'[Watcher appears — very close]\nWATCHER:\n"You listened to them."'},
  {t:'CHUG:\n"…No."'},
  {t:'WATCHER:\n"You believed them."'},
  {t:'WATCHER:\n"…And I paid for it."'},
  {t:'CHUG:\n"…I don\'t even know who you are."\nWATCHER:\n"…That\'s the worst part."'},
  {t:'[Watcher steps back slowly]'},
  {t:'[Watcher gone]\n\nCHUG stands alone.'},
  {t:'CHUG (low):\n"…Why does this feel real?"'},
  {t:'GUIDE (quiet):\n"…Because it is."'},
  {t:'SYSTEM: "DESCEND FURTHER?"'},

  {t:'[EXPANDED ENCOUNTER — LEFT BEHIND]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:7},
  {t:'[EXPANDED ENCOUNTER — LEFT BEHIND]\\nAMBUSH WAVE. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:9},
  {t:'— END OF PART 4 —',end:true},

  // PART 5
  {part:5,t:'PART 5 — CONTROLLED',col:'#cc00aa'},
  {t:'[Deeper layer | red cracks across ground | unstable air]\nSFX: distorted breathing'},
  {t:'CHUG: "…Something\'s here."\nGUIDE: "Yes."'},
  {t:'GUIDE: "And it\'s not just watching anymore."'},
  {t:'SYSTEM: "FOREIGN PRESENCE DETECTED"',col:'#cc00aa'},
  {t:'CHUG: "…Foreign?"\nGUIDE: "…Someone who doesn\'t belong here."'},
  {t:'[Far distance — a figure kneeling]\nHead down. Not moving.\n\nCHUG walks slowly.'},
  {t:'CHUG: "…Hey."\n\n[No response]'},
  {t:'[As Chug gets closer, space distorts]\n[Figure twitches unnaturally]',gl:true},
  {t:'VOICE (LOW, BROKEN):\n"…Stay… back…"\n\nCHUG: "…You can talk?"'},
  {t:'[Sudden black pulse from above]',gl:true},
  {t:'CONTROLLED FIGURE:\n"…Target acquired."\n\nCHUG: "…What—?"'},
  {t:'SYSTEM: "ANOMALY — HOST DETECTED"',col:'#cc00aa'},
  {t:'CONTROLLED FIGURE:\n"…Execute."'},
  {t:'SYSTEM: COMBAT PROTOCOL',fight:11},
  {t:'[Boss fights aggressively — erratically]'},
  {t:'CONTROLLED FIGURE:\n"…Stop…"\n"…Don\'t…"\n"…Attack…"',gl:true},
  {t:'CHUG: "…You\'re not doing this on your own."'},
  {t:'[Boss suddenly stops mid-attack]\n\nVOICE (CLEAR, HUMAN):\n"…Chug…?"',gl:true},
  {t:'CHUG freezes.\n\nCHUG: "…You know me?"'},
  {t:'[Instant glitch — control resumes]',gl:true},
  {t:'CONTROLLED FIGURE:\n"…Eliminate."'},
  {t:'GUIDE (low):\n"…This is new."\nCHUG: "What is he?"\nGUIDE: "…A puppet."'},
  {t:'[Chug lands finishing combo]\n[Boss collapses]'},
  {t:'[Dark energy leaks out and vanishes upward]',col:'#cc00aa'},
  {t:'SYSTEM: "CONTROL LINK PARTIALLY SEVERED"',col:'#cc00aa'},
  {t:'[Chug kneels near him]\nFace still partly shadowed.\nBREATHING: weak'},
  {t:'FIGURE:\n"…What… happened…"\n\nCHUG: "…You attacked me."'},
  {t:'FIGURE:\n"…No… I… wouldn\'t…"\n\n[He looks confused]'},
  {t:'[Figure looks up — still not fully clear]\nFIGURE:\n"…Chug…?"',gl:true},
  {t:'CHUG: "…Yeah."\n\n[Pause]\n\nFIGURE:\n"…It\'s me…"'},
  {t:'[Glitch interrupts before name fully stabilizes]',gl:true},
  {t:'FIGURE:\n"…I can\'t… remember…"\n\n[Memory fragments flicker and disappear]'},
  {t:'SYSTEM: "MEMORY CORRUPTION DETECTED"',col:'#cc00aa',gl:true},
  {t:'[Figure collapses unconscious]\n\nCHUG:\n"…Who are you?"'},
  {t:'GUIDE:\n"…Someone important."\n\nCHUG:\n"…Then why don\'t I remember him?"'},
  {t:'GUIDE:\n"…Because someone doesn\'t want you to."'},
  {t:'[Above — faint Watcher silhouette for a split second]\n\nWATCHER (DISTANT):\n"…Not yet."',gl:true},
  {t:'CHUG stands over unconscious body.\n\nCHUG (low):\n"…Why did he call my name?"'},
  {t:'GUIDE:\n"…Because he knows you."'},
  {t:'SYSTEM: "PROCEED?"'},

  {t:'[EXPANDED ENCOUNTER — CONTROLLED]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:9},
  {t:'[EXPANDED ENCOUNTER — CONTROLLED]\\nAMBUSH WAVE. The chapter breathes breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:12},
  {t:'[EXPANDED ENCOUNTER — CONTROLLED]\\nPRESSURE TEST. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:16},
  {t:'— END OF PART 5 —',end:true},

  // PART 6
  {part:6,t:'PART 6 — VANISHED',col:'#cc4400'},
  {t:'[Same area | ash drifting]\n[Chug looks down]\n\n…Body gone.',col:'#cc4400'},
  {t:'CHUG: "…What?"\n\n[Only cracks remain where he fell]'},
  {t:'CHUG:\n"No… he was right here."'},
  {t:'GUIDE:\n"…He was taken."\n\nCHUG:\n"By who?"\n\n[Silence]'},
  {t:'[Ground flickers — glitch trail forward]',gl:true},
  {t:'SYSTEM: "RESIDUAL SIGNAL DETECTED"',col:'#cc4400'},
  {t:'CHUG: "…He\'s still here."\nGUIDE:\n"…No."\nGUIDE:\n"He\'s being moved."'},
  {t:'[Chug follows the signal]\n\nVOICE (DISTANT):\n"…Chug…"',gl:true},
  {t:'CHUG: "…That\'s him."\nGUIDE:\n"…Or what\'s left of him."'},
  {t:'[Enemies spawn — more precise, less chaotic]\nENEMIES:\n"Adapt."\n"Learn."\n"Improve."'},
  {t:'CHUG: "…They\'re changing."\nGUIDE:\n"They\'re evolving."'},
  {t:'SYSTEM: EVOLVED WAVE',fight:12},
  {t:'[Enemy freezes mid fight]\n[Black pulse hits — instantly upgrades]',gl:true},
  {t:'SYSTEM: "CONTROL OVERRIDE ACTIVE"',col:'#cc4400',gl:true},
  {t:'CHUG: "…That\'s the same thing from before."\nGUIDE:\n"…Yes."'},
  {t:'GUIDE:\n"He\'s controlling them."'},
  {t:'CHUG:\n"…Then that guy…"\nGUIDE:\n"…Wasn\'t the first."'},
  {t:'[Broken screen appears]\n[Clip: unknown person beside Chug]'},
  {t:'VOICE:\n"Don\'t go solo yet."\n\nCHUG: "…I said no…"\n\n[Clip distorts]',gl:true},
  {t:'CHUG:\n"…Did I leave him?"\nGUIDE:\n"…You chose to move forward."'},
  {t:'CHUG:\n"That\'s not the same."\nGUIDE:\n"…To you."'},
  {t:'[Glitch trail intensifies]\n[Red + black pulses overlapping]',gl:true},
  {t:'SYSTEM: "HOST RELOCATED"',col:'#cc4400'},
  {t:'CHUG: "…Host…"\nGUIDE:\n"…The one you fought."\n\nCHUG:\n"…He\'s still alive."'},
  {t:'[Environment freezes briefly]\n\n[Watcher appears — very close, behind Chug]'},
  {t:'WATCHER:\n"You broke it."'},
  {t:'CHUG turns.\n\nCHUG:\n"…You did this."'},
  {t:'WATCHER:\n"I improved it."'},
  {t:'CHUG:\n"He\'s not yours."\nWATCHER:\n"…He chose to stay behind."'},
  {t:'CHUG:\n"…You\'re lying."\nWATCHER:\n"…Then why don\'t you remember him?"'},
  {t:'[Watcher disappears instantly]\n\nCHUG:\n"…No."'},
  {t:'GUIDE (quiet):\n"…You\'re starting to see it."'},
  {t:'[Multiple enemies attack in sync]\nPerfect coordination.\nENEMIES:\n"Force error."\n"Punish hesitation."'},
  {t:'SYSTEM: "SYNC PRESSURE ↑"'},
  {t:'SYSTEM: SYNC WAVE',fight:13},
  {t:'[Enemies dissolve together]\n\nCHUG breathing heavy.'},
  {t:'CHUG:\n"…This isn\'t just fighting."\nGUIDE:\n"…No."'},
  {t:'GUIDE:\n"It\'s training."'},
  {t:'[Signal leads deeper]\n\nVOICE (barely audible):\n"…help…"',gl:true},
  {t:'CHUG:\n"…I\'m coming."'},
  {t:'GUIDE:\n"…Be careful."'},
  {t:'CHUG:\n"No."\n\nCHUG:\n"…This time I won\'t be late."'},
  {t:'[Chug steps into deeper void]\n\nSYSTEM: "ENTER NEXT LAYER?"',col:'#cc4400'},

  {t:'[EXPANDED ENCOUNTER — VANISHED]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:12},
  {t:'[EXPANDED ENCOUNTER — VANISHED]\\nAMBUSH WAVE. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:16},
  {t:'— END OF PART 6 —',end:true},

  // PART 7
  {part:7,t:'PART 7 — REWRITE',col:'#aa0055'},
  {t:'[New layer | darker | ground pulsing faint red]\nSFX: rhythmic glitch pulse',col:'#aa0055'},
  {t:'CHUG: "…He\'s here."\nGUIDE: "…Yes."'},
  {t:'[Glitch trail stabilizes into fixed point ahead]',gl:true},
  {t:'SYSTEM: "HOST SIGNAL LOCKED"',col:'#aa0055'},
  {t:'CHUG: "…I found you."'},
  {t:'[Figure stands center, back turned]\nStill. Too still.\n\nCHUG: "…Hey."'},
  {t:'[Figure slowly turns]\nMovement smoother… but wrong.'},
  {t:'CONTROLLED HOST:\n"…You\'re late."'},
  {t:'CHUG: "…What did you say?"'},
  {t:'SYSTEM: "HOST REINITIALIZED"',col:'#aa0055'},
  {t:'CONTROLLED HOST:\n"…Previous errors removed."'},
  {t:'CHUG: "…You\'re not talking like before."'},
  {t:'CONTROLLED HOST:\n"…Engage target."'},
  {t:'[Brief glitch]\n\nVOICE (WEAK, HUMAN):\n"…Run…"',gl:true},
  {t:'[Instant override]\n\nCONTROLLED HOST:\n"…Eliminate."'},
  {t:'SYSTEM: REWRITE PROTOCOL',fight:14},
  {t:'[Combat — cleaner, faster, perfect counters]\nNo hesitation. Predicts inputs.'},
  {t:'CHUG: "…He\'s stronger."\nGUIDE:\n"…He\'s refined."'},
  {t:'[Chug lands hit — control flickers]',gl:true},
  {t:'VOICE (CLEARER):\n"…Chug… don\'t…"'},
  {t:'CHUG:\n"…You know me."'},
  {t:'[Control snaps back]\n\nCONTROLLED HOST:\n"…Irrelevant."'},
  {t:'[Boss enters overdrive — red + black aura]',gl:true},
  {t:'SYSTEM: "CONTROL PRIORITY ↑"',col:'#aa0055',gl:true},
  {t:'CONTROLLED HOST:\n"…Correct mistakes."'},
  {t:'CHUG:\n"…Stop fighting it!"'},
  {t:'GUIDE (lower):\n"…He can\'t."\nCHUG: "What do you mean?"'},
  {t:'GUIDE:\n"…He\'s being rewritten."'},
  {t:'[Chug forces opening — lands heavy combo]\n[Boss staggers]'},
  {t:'CONTROLLED HOST:\n"…System… unstable…"'},
  {t:'[Control weakens briefly]',gl:true},
  {t:'VOICE (HUMAN):\n"…Why… did you…"'},
  {t:'CHUG:\n"…Say it."'},
  {t:'VOICE:\n"…leave…"'},
  {t:'[Control slams back in]\n\nCONTROLLED HOST:\n"…Finish."'},
  {t:'[Chug wins — boss collapses]\nSFX: heavy glitch crack',gl:true},
  {t:'SYSTEM: "CONTROL LINK DAMAGED"',col:'#aa0055'},
  {t:'[Figure breathing normally]\n\nFIGURE:\n"…I… can\'t… remember…"'},
  {t:'CHUG:\n"…It\'s me."\nFIGURE:\n"…I know…"'},
  {t:'[Pause]\n\nFIGURE:\n"…but I don\'t…"'},
  {t:'FIGURE:\n"…Ch—"\n\n[Audio cuts abruptly]',gl:true},
  {t:'SYSTEM: "MEMORY BLOCK ENFORCED"',col:'#aa0055',gl:true},
  {t:'[Black pulse strikes from above]\n[Figure freezes completely]',gl:true},
  {t:'WATCHER (DISTANT):\n"…Not yet."'},
  {t:'[Figure vanishes instantly]'},
  {t:'CHUG:\n"…NO."'},
  {t:'[Silence]\n\nCHUG:\n"…He was right there."'},
  {t:'GUIDE:\n"…And now he\'s deeper."'},
  {t:'CHUG:\n"…Why can\'t I remember him?"'},
  {t:'GUIDE:\n"…Because remembering breaks the system."'},
  {t:'CHUG:\n"…What system?"\n\n[Pause]'},
  {t:'GUIDE:\n"…The one you\'re inside."'},
  {t:'[Path ahead opens — darker than before]\n\nVOICE:\n"…don\'t forget me…"',gl:true},
  {t:'CHUG (low):\n"…I won\'t."'},
  {t:'SYSTEM: "GO FURTHER?"',col:'#aa0055'},

  {t:'[EXPANDED ENCOUNTER — REWRITE]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:16},
  {t:'[EXPANDED ENCOUNTER — REWRITE]\\nAMBUSH WAVE. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:17},
  {t:'[EXPANDED ENCOUNTER — REWRITE]\\nPRESSURE TEST. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:3},
  {t:'— END OF PART 7 —',end:true},

  // PART 8
  {part:8,t:'PART 8 — FRAGMENTS',col:'#660033'},
  {t:'[Deeper layer | environment unstable, flickering between void & old room]\nSFX: overlapping audio — stream + silence',col:'#660033'},
  {t:'CHUG:\n"…This place is breaking."'},
  {t:'GUIDE:\n"No."'},
  {t:'GUIDE:\n"You are."'},
  {t:'[Chug walks — environment suddenly shifts into his old streaming room]\n\n[RGB lights… desk… mic… two chairs]'},
  {t:'CHUG freezes.',col:'#660033'},
  {t:'CHUG:\n"...This is real."'},
  {t:'[Second chair slightly pulled back]'},
  {t:'[Someone sitting in second chair… blurred silhouette]'},
  {t:'VOICE:\n"You ready?"'},
  {t:'CHUG:\n"…Yeah."'},
  {t:'[Pause]\n\nCHUG:\n"…Wait…"'},
  {t:'[Everything glitches violently — scene collapses]',gl:true},
  {t:'SYSTEM: "MEMORY ACCESS DETECTED"',col:'#660033'},
  {t:'SYSTEM: "CORRUPTION INITIATED"',col:'#660033',gl:true},
  {t:'[Enemies spawn instantly]',col:'#660033'},
  {t:'ENEMIES:\n"Erase it."\n"Stop recall."'},
  {t:'CHUG:\n"…They don\'t want me to remember."'},
  {t:'[Enemies faster, aggressive, coordinated]\n[Each hit causes visual glitches]'},
  {t:'SYSTEM: "STABILITY ↓"',col:'#660033'},
  {t:'CHUG:\n"…It\'s attacking my memory."'},
  {t:'SYSTEM: MEMORY ERASURE WAVE',fight:15},
  {t:'[Enemies destroyed]\n\n[Fragments of room flicker again]'},
  {t:'VOICE (CLEARER):\n"Don\'t rush it."'},
  {t:'CHUG:\n"…That\'s him."'},
  {t:'GUIDE:\n"You\'re pushing too fast."'},
  {t:'CHUG:\n"I need to know."'},
  {t:'GUIDE:\n"…If you force it, you\'ll lose everything."'},
  {t:'CHUG:\n"…I already did."'},
  {t:'[Environment freezes]\n\n[Watcher appears — closer than ever]'},
  {t:'WATCHER:\n"You\'re breaking the sequence."'},
  {t:'CHUG:\n"You\'re hiding him."'},
  {t:'WATCHER:\n"…I\'m protecting what\'s left."'},
  {t:'CHUG:\n"You\'re controlling him."'},
  {t:'WATCHER:\n"…I\'m preserving him."'},
  {t:'CHUG:\n"…From me?"'},
  {t:'[Pause]\n\nWATCHER:\n"…Yes."'},
  {t:'CHUG:\n"…Then let him go."'},
  {t:'WATCHER:\n"…You couldn\'t hold him before."'},
  {t:'[Silence hits]'},
  {t:'WATCHER:\n"…Why would I trust you now?"'},
  {t:'[Watcher vanishes]',gl:true},
  {t:'[Massive glitch surge]\n[Full scene flashes clearly for a second]',gl:true},
  {t:'[Chug + friend laughing together]'},
  {t:'FRIEND:\n"If you go big… I\'m with you."'},
  {t:'CHUG:\n"…Always?"'},
  {t:'FRIEND:\n"…Always."'},
  {t:'[Scene shatters instantly]',gl:true},
  {t:'[Chug drops to knee]'},
  {t:'CHUG:\n"…I remember…"'},
  {t:'[Head hurts — glitch interference]',gl:true},
  {t:'SYSTEM: "RECALL BLOCKED"',col:'#660033',gl:true},
  {t:'[Signal spikes violently]',gl:true},
  {t:'SYSTEM: "HOST INSTABILITY ↑"',col:'#660033'},
  {t:'GUIDE:\n"…He\'s breaking."'},
  {t:'CHUG:\n"…Good."'},
  {t:'GUIDE:\n"…No."'},
  {t:'GUIDE:\n"If he breaks… he\'s gone."'},
  {t:'CHUG:\n"…Then I\'ll fix it."'},
  {t:'GUIDE:\n"…You couldn\'t before."'},
  {t:'CHUG:\n"…I didn\'t try."'},
  {t:'[Silence]'},
  {t:'[Voice echoes clearly now]'},
  {t:'VOICE:\n"…Don\'t forget me…"',gl:true},
  {t:'CHUG:\n"…I won\'t."'},
  {t:'[Path splits into two directions]'},
  {t:'SYSTEM:\n"STABILIZE"\n"PURSUE"',col:'#660033'},
  {t:'CHUG looks forward.'},
  {t:'CHUG (low):\n"…I\'m coming."'},

  {t:'[EXPANDED ENCOUNTER — FRAGMENTS]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:17},
  {t:'[EXPANDED ENCOUNTER — FRAGMENTS]\\nAMBUSH WAVE. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:3},
  {t:'[EXPANDED ENCOUNTER — FRAGMENTS]\\nPRESSURE TEST. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:6},
  {t:'— END OF PART 8 —',end:true},

  // PART 9
  {part:9,t:'PART 9 — BREAKPOINT',col:'#880022'},
  {t:'[Two paths: STABILIZE / PURSUE]\nCHUG doesn\'t hesitate — walks forward.',col:'#880022'},
  {t:'SYSTEM: "PURSUIT CONFIRMED"',col:'#880022'},
  {t:'GUIDE:\n"…You\'re risking everything."'},
  {t:'CHUG:\n"…I already lost it."'},
  {t:'[Environment unstable — enemies spawn unpredictably]'},
  {t:'SYSTEM: "RANDOM ENCOUNTERS ACTIVE"',col:'#880022'},
  {t:'ENEMIES:\n"Interrupt."\n"Delay."\n"Reset him."'},
  {t:'SYSTEM: INTERFERENCE WAVE',fight:16},
  {t:'CHUG:\n"…Now they\'re stalling me."'},
  {t:'GUIDE:\n"…They\'re buying time."'},
  {t:'[Flash: duo stream again — clearer]',gl:true},
  {t:'FRIEND:\n"Don\'t go solo yet."'},
  {t:'CHUG:\n"…I didn\'t listen."'},
  {t:'[Enemy waves increase in speed + frequency]'},
  {t:'SYSTEM: "PRESSURE ↑"',col:'#880022'},
  {t:'CHUG:\n"…Enough."'},
  {t:'SYSTEM: "RAGE ACTIVE"',col:'#880022',gl:true},
  {t:'SYSTEM: PRESSURE WAVE',fight:17},
  {t:'[Area locks — ground cracks open]',col:'#880022'},
  {t:'SYSTEM: "SUB BOSS DETECTED"',col:'#880022'},
  {t:'[Figure drops from above — masked, faster than previous enemies]'},
  {t:'SUB BOSS:\n"…Delay the subject."'},
  {t:'CHUG:\n"…You\'re not him."'},
  {t:'SUB BOSS:\n"…No. Just necessary."'},
  {t:'[Combat — high speed, counter-heavy, punishes mistakes]'},
  {t:'SUB BOSS:\n"Predictable."\n"Late."\n"Weak."'},
  {t:'CHUG:\n"…Shut up."'},
  {t:'SYSTEM: SUB BOSS — THE DELAY',fight:18},
  {t:'[Sub Boss glitches briefly]',gl:true},
  {t:'VOICE (UNKNOWN):\n"…Why are you stopping him?"',gl:true},
  {t:'[Control snaps back]\n\nSUB BOSS:\n"…Irrelevant."'},
  {t:'[Chug lands final combo]\n[Sub Boss shatters into fragments]',gl:true},
  {t:'SYSTEM: "OBSTRUCTION REMOVED"',col:'#880022'},
  {t:'[Fragments float — then dissolve]'},
  {t:'GUIDE:\n"…They\'re sending layers now."'},
  {t:'CHUG:\n"…He\'s getting closer."'},
  {t:'[Massive pulse — red + black]',gl:true},
  {t:'SYSTEM: "HOST CRITICAL STATE"',col:'#880022',gl:true},
  {t:'CHUG:\n"…He\'s there."'},
  {t:'[Environment freezes]\n[Watcher appears — but flickering]',gl:true},
  {t:'WATCHER:\n"…Stop."'},
  {t:'WATCHER:\n"…You\'re not supposed to reach this."'},
  {t:'CHUG:\n"…You\'re losing control."'},
  {t:'WATCHER:\n"…You forced this."'},
  {t:'CHUG:\n"…Let him go."'},
  {t:'WATCHER:\n"…You already did that once."'},
  {t:'[Silence]'},
  {t:'[Massive flash — clearest yet]',gl:true},
  {t:'[Chug + friend standing together]'},
  {t:'FRIEND:\n"If we blow up… we do it together."'},
  {t:'CHUG:\n"…Yeah."'},
  {t:'FRIEND:\n"…Don\'t leave me behind."'},
  {t:'CHUG:\n"…Ya—"'},
  {t:'[Audio distortion cuts it]',gl:true},
  {t:'SYSTEM: "IDENTITY BLOCKED"',col:'#880022',gl:true},
  {t:'CHUG:\n"…NO."'},
  {t:'[Random enemies spawn aggressively]'},
  {t:'SYSTEM: "INTERFERENCE MAX"',col:'#880022'},
  {t:'ENEMIES:\n"Erase him."\n"Stop recall."'},
  {t:'CHUG:\n"…I\'m not stopping."'},
  {t:'SYSTEM: FINAL INTERFERENCE',fight:19},
  {t:'[Chug clears all enemies]\n[Path opens violently]',gl:true},
  {t:'SFX: loud crack\n\nGUIDE:\n"…You\'re at the edge."'},
  {t:'CHUG:\n"…Good."'},
  {t:'[Voice clearer than ever]'},
  {t:'VOICE:\n"…Chug…"',gl:true},
  {t:'[Pause]\n\nVOICE:\n"…help me…"',gl:true},
  {t:'CHUG steps forward.'},
  {t:'CHUG (low, shaking):\n"…I\'m coming."'},
  {t:'SYSTEM: "FINAL LAYER AHEAD"',col:'#880022'},
  {t:'— END OF PART 9 —',end:true},

  // PART 10
  {part:10,t:'PART 10 — ERASURE',col:'#cc0033'},
  {t:'[Darkest zone yet | ground fractured | sky unstable]\nSFX: constant glitch + heartbeat',col:'#cc0033',gl:true},
  {t:'SYSTEM: "FINAL HOST ZONE"',col:'#cc0033'},
  {t:'CHUG:\n"…This is it."'},
  {t:'GUIDE:\n"…Yes."'},
  {t:'[Center — figure standing still]\nNo movement. No distortion. Calm.'},
  {t:'CHUG:\n"…You."'},
  {t:'[Figure slowly lifts head]'},
  {t:'[No erratic motion now — perfectly controlled]'},
  {t:'HOST:\n"…You made it."'},
  {t:'CHUG:\n"…Who are you?"'},
  {t:'[Pause]\n\nHOST:\n"…You already know."'},
  {t:'[Above — faint shadow pulse]',gl:true},
  {t:'WATCHER (DISTANT):\n"…Finish it."'},
  {t:'[Host\'s eyes glow stronger]',gl:true},
  {t:'SYSTEM: "HOST — FULL CONTROL"',col:'#cc0033'},
  {t:'HOST:\n"…No more interruptions."'},
  {t:'SYSTEM: FINAL HOST — FULL CONTROL',fight:20},
  {t:'[Perfect mirror combat — faster than before]'},
  {t:'CHUG:\n"…He knows everything I\'ll do."'},
  {t:'GUIDE:\n"…Because he learned from you."'},
  {t:'[Chug lands strong hit]\n[Control flickers]',gl:true},
  {t:'VOICE (CLEAR):\n"…Chug…"'},
  {t:'CHUG:\n"…Say it."'},
  {t:'VOICE:\n"…Why did you—"\n\n[Override]\n\nHOST:\n"…Continue."',gl:true},
  {t:'[Black + red aura explodes]',col:'#cc0033',gl:true},
  {t:'SYSTEM: "OVERWRITE MODE"',col:'#cc0033',gl:true},
  {t:'HOST:\n"…Remove error."'},
  {t:'[Attacks become brutal, nonstop]\n\nCHUG struggling.'},
  {t:'CHUG:\n"…I\'m not losing you again."'},
  {t:'GUIDE:\n"…Then stop fighting like before."'},
  {t:'CHUG:\n"…Then how?"\n\nGUIDE:\n"…Remember."'},
  {t:'[Massive flash — full clarity for a second]',gl:true},
  {t:'[Chug + friend side by side]'},
  {t:'FRIEND:\n"If we rise… we rise together."'},
  {t:'CHUG:\n"…Always."'},
  {t:'FRIEND smiles.'},
  {t:'[Chug changes timing — unpredictable attack]\n[Breaks through guard]'},
  {t:'[Massive hit lands]\n\nSFX: shatter + glitch collapse',gl:true},
  {t:'[Dark energy explodes out of host]',gl:true},
  {t:'SYSTEM: "CONTROL LINK DESTROYED"',col:'#cc0033',gl:true},
  {t:'[Host collapses]'},
  {t:'[No sound]\n\n[Chug slowly walks toward him]'},
  {t:'CHUG:\n"…It\'s over."'},
  {t:'[Chug kneels down]\n[Gets close for the first time]'},
  {t:'[Face visible]\n\n[Chug goes still]'},
  {t:'CHUG (barely a whisper):\n"…Yassine."'},
  {t:'[Silence]\n\n[No response]'},
  {t:'CHUG:\n"…It\'s me."\n\n[Pause]\n\nCHUG:\n"…Open your eyes."'},
  {t:'[Host breathing normally now]'},
  {t:'HOST:\n"…What… happened…"'},
  {t:'CHUG:\n"…You were controlled."'},
  {t:'HOST:\n"…Controlled…?"\n\n[Looks confused]'},
  {t:'CHUG:\n"…Yassine. It\'s me."'},
  {t:'HOST:\n"…"\n\n[Eyes unfocused]\n\n[No recognition]'},
  {t:'[Glitch flicker]',gl:true},
  {t:'SYSTEM: "MEMORY RESET INITIATED"',col:'#cc0033',gl:true},
  {t:'HOST:\n"…Who… are you…?"'},
  {t:'CHUG freezes.'},
  {t:'CHUG:\n"…You don\'t remember me?"'},
  {t:'HOST:\n"…Should I…?"'},
  {t:'[Silence hits HARD]'},
  {t:'CHUG:\n"…We fought together."'},
  {t:'HOST:\n"…I don\'t remember that."'},
  {t:'[Light pulls host away slowly]',gl:true},
  {t:'CHUG:\n"WAIT—"'},
  {t:'[He vanishes]',gl:true},
  {t:'[Empty space]'},
  {t:'CHUG:\n"…No…"'},
  {t:'GUIDE:\n"…You saved him."'},
  {t:'CHUG:\n"…I lost him."'},
  {t:'[Very faint voice]',gl:true},
  {t:'VOICE:\n"…sorry…"',gl:true},
  {t:'[Gone]'},
  {t:'CHUG stands alone.'},
  {t:'CHUG (low):\n"…Who was he?"'},
  {t:'[Pause]\n\nGUIDE:\n"…That\'s the problem."'},
  {t:'GUIDE:\n"…You still don\'t know."'},
  {t:'SYSTEM: "NEXT PHASE UNLOCKED"',col:'#cc0033'},

  {t:'[EXPANDED ENCOUNTER — ERASURE]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:6},
  {t:'[EXPANDED ENCOUNTER — ERASURE]\\nAMBUSH WAVE. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:8},
  {t:'[EXPANDED ENCOUNTER — ERASURE]\\nPRESSURE TEST. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:10},
  {t:'— END OF PART 10 —',end:true},

  // PART 11
  {part:11,t:'PART 11 — AFTERIMAGE',col:'#334455'},
  {t:'[Environment stabilizes slightly | low echo]\nCHUG stands still.',col:'#334455'},
  {t:'CHUG:\n"…It\'s over."'},
  {t:'GUIDE:\n"…For now."'},
  {t:'[Light distortion forms nearby]\n[Figure appears — normal, no glow]'},
  {t:'CHUG:\n"…Yassine."'},
  {t:'FIGURE:\n"…Yeah…?"\n\n[Confused, steady breathing]'},
  {t:'CHUG:\n"…Wait."\n\n[Pause]\n\nCHUG:\n"…You responded."'},
  {t:'FIGURE:\n"…Is that my name?"'},
  {t:'[Silence hits hard]'},
  {t:'CHUG:\n"…What happened to you?"'},
  {t:'FIGURE:\n"…I don\'t know."'},
  {t:'CHUG:\n"…You were fighting me."'},
  {t:'FIGURE:\n"…No… I just got here."\n\n[No hesitation. Genuine.]'},
  {t:'CHUG:\n"…Do you remember anything?"'},
  {t:'FIGURE:\n"…Just… waking up."'},
  {t:'[Pause]\n\nFIGURE:\n"…Do I know you?"'},
  {t:'CHUG:\n"…Yeah."\n\n[Pause]\n\nCHUG:\n"…We did everything together."'},
  {t:'[Silence hits]'},
  {t:'FIGURE:\n"…What\'s my name?"\n\n[Beat]\n\nFIGURE:\n"My full name."'},
  {t:'[Chug freezes]\n\nCHUG:\n"…Yassine."\n\n[Pause]\n\nCHUG:\n"…I don\'t know your last name."'},
  {t:'FIGURE:\n"…"\n\n[Neither do I]'},
  {t:'CHUG:\n"…We were partners."\n\n[Words stop]'},
  {t:'SYSTEM: "MEMORY BLOCK ACTIVE"',col:'#334455'},
  {t:'CHUG:\n"…I can\'t remember anything else."'},
  {t:'GUIDE:\n"…The block goes both ways."'},
  {t:'[Figure looks around, steady now]'},
  {t:'FIGURE:\n"…This place feels wrong."'},
  {t:'CHUG:\n"…Yeah."'},
  {t:'FIGURE:\n"…But I\'m fine."\n\n[No corruption. No control.]'},
  {t:'[Space slowly shifts, separating them]'},
  {t:'CHUG:\n"…Stay."'},
  {t:'FIGURE:\n"…For what?"\n\n[Pause]\n\nCHUG has no answer.'},
  {t:'FIGURE:\n"…If we knew each other… we\'ll meet again."'},
  {t:'CHUG:\n"…Yeah."'},
  {t:'[Light pulls him away slowly]',gl:true},
  {t:'[Chug alone again]'},
  {t:'CHUG:\n"…Why does that feel wrong?"'},
  {t:'GUIDE:\n"…Because something is missing."'},
  {t:'[Massive distortion wave]',gl:true},
  {t:'SYSTEM: "FUTURE THREADS DETECTED"',col:'#334455',gl:true},
  {t:'[Multiple silhouettes flash]',gl:true},
  {t:'[12 armored silhouettes appear, heavy presence]'},
  {t:'SYSTEM: "UNKNOWN FACTION: DRAKOS (12)"',col:'#334455'},
  {t:'[Disappear instantly]\n\nCHUG:\n"…Twelve?"'},
  {t:'[6 fast silhouettes dash across]',gl:true},
  {t:'SYSTEM: "UNKNOWN FACTION: NEXTERS (6)"',col:'#334455'},
  {t:'[Gone]\n\nCHUG:\n"…Fast…"'},
  {t:'[More flashes — different fighters]\n\n— Blade user\n— Giant brute\n— Masked assassin\n— Dual wielder\n\nAll vanish.',gl:true},
  {t:'GUIDE:\n"…These aren\'t memories."'},
  {t:'CHUG:\n"…Then what?"\n\nGUIDE:\n"…Future."'},
  {t:'CHUG:\n"…So this doesn\'t end here."'},
  {t:'GUIDE:\n"…It hasn\'t even started."'},
  {t:'[Very faint voice — almost gone]',gl:true},
  {t:'VOICE:\n"…don\'t forget…"',gl:true},
  {t:'CHUG:\n"…I don\'t even know what I lost."'},
  {t:'[Massive path opens ahead]',gl:true},
  {t:'SYSTEM:\n"NEW THREATS UNLOCKED"',col:'#334455'},
  {t:'CHUG steps forward.'},
  {t:'CHUG (low):\n"…Then I\'ll find out."'},

  {t:'[EXPANDED ENCOUNTER — AFTERIMAGE]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:8},
  {t:'[EXPANDED ENCOUNTER — AFTERIMAGE]\\nAMBUSH WAVE. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:10},
  {t:'[EXPANDED ENCOUNTER — AFTERIMAGE]\\nPRESSURE TEST. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:11},
  {t:'[EXPANDED ENCOUNTER — AFTERIMAGE]\\nELITE SKIRMISH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:1},
  {t:'— END OF PART 11 —',end:true},

  // PART 12
  {part:12,t:'PART 12 — AROWH',col:'#1a1a2e'},
  {t:'[New layer | ground cracked | air heavy]\n\nCHUG: "…This pressure…"',col:'#1a1a2e'},
  {t:'GUIDE: "…Different class."'},
  {t:'[3 shadows emerge from the dark]'},
  {t:'SYSTEM: "RANDOM ENCOUNTER — 3 UNITS"',col:'#334455'},
  {t:'ENEMIES: "Engage."',fight:1},
  {t:'[All 3 down]\n\nCHUG: "…Too easy."'},
  {t:'[Silence]'},
  {t:'[Ground trembles]\n[Massive shadow forms]',gl:true},
  {t:'[Figure lands]\n\nTall. Armored. Unmoving.'},
  {t:'SYSTEM: "DRAKO UNIT DETECTED"',col:'#cc0000'},
  {t:'SYSTEM: "ID: NO.12 — AROWH"',col:'#cc0000'},
  {t:'CHUG: "…You\'re the heavy one."'},
  {t:'[No response]\n\nGUIDE (low): "…Don\'t rush this."'},
  {t:'[Chug attacks first]\n[Hits land… no reaction]'},
  {t:'CHUG: "…What?"'},
  {t:'[AROWH slowly lifts arm]\n\nSingle strike.',fight:21},
  {t:'[Chug sent flying]\n\nAROWH: "…Weak."'},
  {t:'CHUG: "…I barely touched him."\n\nGUIDE: "…You didn\'t."'},
  {t:'SYSTEM: "RAGE ACTIVE"',col:'#cc0000'},
  {t:'[Fast combo barrage]\n[AROWH blocks everything]\n[Grabs Chug mid-attack]',fight:21},
  {t:'AROWH: "…Predictable."\n\n[Releases him]\n[Steps back. Doesn\'t finish.]'},
  {t:'[Chug pinned]\n\nCHUG: "…Fight me properly."'},
  {t:'AROWH: "…You\'re not worth it."'},
  {t:'[Chug charges — tries unpredictability]\n[Lands one clean hit]'},
  {t:'CHUG: "…I got—"\n\n[Instant counter]\n[Massive blow.]',fight:21},
  {t:'[Chug crashes hard. Can\'t stand.]\n\nAROWH stands over him.'},
  {t:'AROWH: "…Still weak."\n\n[Turns away]'},
  {t:'CHUG: "…Why won\'t you finish it…?"\n\n[AROWH stops]'},
  {t:'AROWH: "…You\'re not a threat."\n\n[Continues walking]'},
  {t:'[AROWH fades into distance]',gl:true},
  {t:'SYSTEM: "DRAKO UNIT WITHDRAWN"',col:'#cc0000'},
  {t:'[3 more shadows appear — hesitating]'},
  {t:'ENEMIES: "…Damaged."\n"…Finish him?"',fight:1},
  {t:'[Chug barely moving]\n\nCHUG (low): "…I couldn\'t even..."'},
  {t:'GUIDE: "…Now you understand."'},
  {t:'CHUG: "…That wasn\'t a fight…"\n\nGUIDE: "…No."'},
  {t:'GUIDE: "…That was a warning."'},
  {t:'SYSTEM: "THREAT LEVEL UPDATED"',col:'#cc0000'},
  {t:'— END OF PART 12 —',end:true},

  // PART 13
  {part:13,t:'PART 13 — FRACTURE',col:'#0d1117'},
  {t:'[Chug alone. Still on the ground.]\n\nCHUG (low):\n"…I couldn\'t dent him."'},
  {t:'GUIDE:\n"…No."'},
  {t:'CHUG:\n"…How do I fight that?"\n\n[Silence]\n\nGUIDE:\n"…You don\'t. Not yet."'},
  {t:'CHUG:\n"…He said No.12."\n\nGUIDE:\n"…Yes."'},
  {t:'CHUG:\n"…There are eleven more like him."\n\n[Long pause]\n\nGUIDE:\n"…At minimum."'},
  {t:'[Brief flicker — memory fragment]',gl:true},
  {t:'[Chug and Yassine. Training. Laughing.]\n\n[Gone instantly]',gl:true},
  {t:'CHUG:\n"…What was that?"\n\nGUIDE:\n"…You\'re starting to remember."'},
  {t:'CHUG:\n"…Why now?"\n\nGUIDE:\n"…Because something broke open."'},
  {t:'CHUG:\n"…Yassine and I… we knew about Drakos."\n\n[Pause]\n\nCHUG:\n"…Didn\'t we."'},
  {t:'GUIDE (quiet):\n"…Keep going."'},
  {t:'[Shadows emerge — fast. Coordinated.]'},
  {t:'SYSTEM: "INTERFERENCE DETECTED — 2 UNITS"',col:'#cc0000'},
  {t:'[They don\'t speak. Just move.]',fight:16},
  {t:'CHUG:\n"…They moved like soldiers."\n\nGUIDE:\n"…They are."'},
  {t:'CHUG:\n"…Drakos trained them."\n\nGUIDE:\n"…Drakos built them."'},
  {t:'[Faint signal. Distorted.]',gl:true},
  {t:'WATCHER (static):\n"…ch—g…"\n\n"…don\'t… trust…"\n\n[Cut]',gl:true},
  {t:'CHUG:\n"…Yassine?"\n\n[Nothing]'},
  {t:'CHUG:\n"…That was him."\n\nGUIDE:\n"…It was a fragment."'},
  {t:'CHUG:\n"…He said don\'t trust."\n\n[Beat]\n\nCHUG:\n"…Was he talking about you?"'},
  {t:'[Long silence]\n\nGUIDE:\n"…I don\'t know."'},
  {t:'[More shadows. Heavier.]'},
  {t:'SYSTEM: "PRESSURE UNIT INCOMING"',col:'#cc0000'},
  {t:'[It doesn\'t wait.]',fight:17},
  {t:'CHUG:\n"…Every fight here drains something."\n\nGUIDE:\n"…Yes."'},
  {t:'CHUG:\n"…What happens if I run out?"\n\nGUIDE:\n"…You become like the others."'},
  {t:'CHUG:\n"…Controlled."\n\nGUIDE:\n"…Erased."'},
  {t:'CHUG:\n"…Why are you helping me?"'},
  {t:'[GUIDE doesn\'t answer immediately]\n\nGUIDE:\n"…Because someone asked me to."'},
  {t:'CHUG:\n"…Who?"\n\nGUIDE:\n"…You already know."'},
  {t:'[One last shadow. Alone. Watching. Calculating.]'},
  {t:'SYSTEM: "EVOLVED UNIT — THREAT ELEVATED"',col:'#cc0000'},
  {t:'[It studied the last three fights before moving.]',fight:12},
  {t:'[Chug stands. Still standing.]\n\nCHUG:\n"…I\'m still here."'},
  {t:'CHUG:\n"…Yassine asked you to protect me."\n\n[Pause]\n\nGUIDE:\n"…He said you\'d figure it out."'},
  {t:'CHUG:\n"…Then I need to get stronger. Fast."\n\nGUIDE:\n"…Win."'},
  {t:'SYSTEM: "MEMORY RECOVERY: 12%"',col:'#334455'},
  {t:'SYSTEM: "DRAKOS UNITS CONFIRMED: 12"',col:'#cc0000'},

  {t:'[EXPANDED ENCOUNTER — FRACTURE]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:11},
  {t:'— END OF PART 13 —',end:true},

  // PART 14 — RECOVERY
  {part:14,t:"PART 14 — RECOVERY",col:'#d4a017'},
  {t:"[SCENE 1 — AFTER AROWH]\n\nThe ground is still cracked.\n\nNo enemies. No sound.\n\nOnly the weight of defeat.\n\nChug stands, slowly… barely holding balance.\n\nCHUG:\n“…I couldn’t even touch him.”\n\nSilence answers.\n\nA faint echo returns.\n\nAROWH (ECHO):\n“…You’re not a threat.”\n\nChug tightens his fist.\n\nCHUG:\n“…Next time… I will be.”"},
  {t:"[SCENE 2 — RETURN]\n\nA soft distortion forms behind him.\n\nChug turns.\n\nYassine stands there.\n\nNo aura. No control. Just… normal.\n\nYASSINE:\n“…You look like you got destroyed.”\n\nCHUG:\n“…You’re back.”\n\nYASSINE:\n“…Was I gone?”\n\nThat line lands quietly.\n\nCHUG:\n“…Yeah.”\n\nYASSINE:\n“…I don’t remember.”\n\nPause.\n\nYASSINE (low):\n“…But I feel like I should know you.”"},
  {t:"[SCENE 3 — DISCONNECT]\n\nChug looks at him.\n\nSomething is there… but incomplete.\n\nCHUG:\n“…We fought together.”\n\nYASSINE:\n“…Did we win?”\n\nCHUG:\n“…I don’t know anymore.”\n\nSilence stretches.\n\nYASSINE:\n“…Then let’s win next time.”"},
  {t:"[SCENE 4 — PHYSICAL STATE]\n\nYassine tries to step forward.\n\nHe stumbles slightly.\n\nCHUG:\n“…You’re still weak.”\n\nYASSINE:\n“…So are you.”\n\nThey almost laugh.\n\nBut don’t."},
  {t:"SYSTEM: FIGHT",fight:3},
  {t:"[SCENE 5 — GUIDE]\n\nGUIDE:\n“…Both of you will die if you fight like this again.”\n\nCHUG:\n“…Then what do we do?”\n\nGUIDE:\n“…Train.”\n\nYASSINE:\n“…With what strength?”\n\nGUIDE:\n“…The kind you don’t have yet.”"},
  {t:"[SCENE 6 — TEACHER ARRIVAL]\n\nA presence forms behind them.\n\nHeavy. Calm. Dangerous.\n\nA man steps forward.\n\nMASTER RAEVAN.\n\nRAEVAN:\n“…So this is the one who challenged a Drako.”\n\nCHUG:\n“…Who are you?”\n\nRAEVAN:\n“…The reason you survive the next one.”"},
  {t:"[SCENE 7 — FIRST LESSON]\n\nRAEVAN:\n“…Attack me.”\n\nChug moves.\n\nFast.\n\nDirect.\n\nRaevan shifts slightly.\n\nBarely.\n\nChug misses.\n\nRaevan taps his chest.\n\nChug stumbles back hard.\n\nCHUG:\n“…That wasn’t even strong.”\n\nRAEVAN:\n“…Exactly.”"},
  {t:"[SCENE 8 — OBSERVATION]\n\nYassine watches silently.\n\nYASSINE:\n“…He didn’t dodge… he moved earlier.”\n\nGUIDE:\n“…Now you’re seeing it.”"},
  {t:"[SCENE 9 — CORE PROBLEM]\n\nRAEVAN:\n“…You react.”\n\nCHUG:\n“…That’s how I fight.”\n\nRAEVAN:\n“…That’s why you lost.”\n\nPause.\n\nRAEVAN:\n“…From now on, you move before you think.”"},
  {t:"[SCENE 10 — TRAINING LOOP]\n\nChug attacks again.\n\nRAEVAN:\n“…Late.”\n\nAgain.\n\nRAEVAN:\n“…Wrong timing.”\n\nAgain.\n\nRAEVAN:\n“…Still weak.”"},
  {t:"SYSTEM: FIGHT",fight:4},
  {t:"[SCENE 11 — YASSINE STEPS IN]\n\nYassine stands.\n\nCHUG:\n“…Sit down. You can’t fight.”\n\nYASSINE:\n“…I’m not staying useless.”\n\nHe steps forward."},
  {t:"SYSTEM: FIGHT",fight:5},
  {t:"[SCENE 12 — YASSINE VS RAEVAN]\n\nYassine attacks.\n\nRough.\n\nUnstable.\n\nBut different.\n\nRaevan pauses.\n\nRAEVAN:\n“…Interesting.”\n\nHe blocks.\n\nPushes Yassine back.\n\nBut not as easily."},
  {t:"[SCENE 13 — DIFFERENCE]\n\nCHUG:\n“…Why was that different?”\n\nRAEVAN:\n“…Because he isn’t thinking.”\n\nYASSINE:\n“…I don’t remember anything.”\n\nRAEVAN:\n“…Good. Then you have no bad habits.”"},
  {t:"[SCENE 14 — TRUTH]\n\nRAEVAN:\n“…Both of you are weak.”\n\nCHUG:\n“…We know.”\n\nRAEVAN:\n“…No. You don’t.”\n\nHe looks directly at Chug.\n\nRAEVAN:\n“…You are weak because you think you’re strong.”"},
  {t:"[SCENE 15 — NEW PATH]\n\nRAEVAN turns away.\n\nRAEVAN:\n“…Training starts now.”\n\nGUIDE:\n“…Listen to him.”\n\nCHUG:\n“…And if I don’t?”\n\nRAEVAN:\n“…Then the next Drako won’t walk away.”"},
  {t:"[SCENE 16 — END]\n\nChug looks at his hands.\n\nShaking.\n\nNot from fear.\n\nFrom realization.\n\nCHUG (low):\n“…I need to change.”\n\nYASSINE:\n“…Then I’ll change too.”\n\nGUIDE:\n“…Good.”\n\nSYSTEM:\n“TRAINING PHASE INITIATED”"},

  {t:'[EXPANDED ENCOUNTER — RECOVERY]\\nSIDE ROUTE CLASH. The chapter breathes through another live combat beat instead of cutting early.'},
  {t:'SYSTEM: FIGHT',fight:1},
  {t:"— END OF PART 14 —",end:true},

  // PART 15 — TIMING
  {part:15,t:"PART 15 — TIMING",col:'#d4a017'},
  {t:"[SCENE 1 — DAWN WITHOUT SUN]\nThe void has no sunrise.\nBut the air still changes.\nThe weight is different.\nThe silence is sharper.\n\nChug stands in the training ground.\nHis arms ache.\nHis ribs hurt.\nHis pride hurts more.\n\nRAEVAN:\nAgain.\n\nCHUG:\n...I just got up.\n\nRAEVAN:\nThen get up better.\n\nYASSINE sits on a broken stone wall nearby.\nHe watches.\nHe says nothing.\n\nGUIDE:\nListen to him.\n\nCHUG:\nI am listening.\n\nRAEVAN:\nNo.\nYou're defending yourself.\nThat isn't listening."},
  {t:"[SCENE 2 — FIRST LOOP]\nRaevan takes one step back.\nHe raises one hand.\n\nRAEVAN:\nStrike.\n\nChug lunges.\nFast.\nDirect.\nClean.\n\nRaevan turns his shoulder.\nChug passes empty air.\n\nRAEVAN:\nLate.\n\nCHUG:\nI moved first.\n\nRAEVAN:\nNo.\nYou moved loud.\n\nYASSINE:\n...Loud?\n\nRAEVAN:\nIntent has weight.\nGood fighters hear it.\nGreat fighters feel it.\nMonsters kill it before it forms.\n\nChug tightens his jaw.\n\nCHUG:\nThen teach me that.\n\nRAEVAN:\nI am.\nYou keep resisting it."},
  {t:"SYSTEM: FIGHT",fight:4},
  {t:"[SCENE 3 — YASSINE SPEAKS]\nYassine drops from the wall.\nHe lands lightly.\nToo lightly.\n\nCHUG:\nYou sure you're okay?\n\nYASSINE:\nNo.\nBut I hate sitting still.\n\nGUIDE:\nHis body remembers motion.\n\nYASSINE:\nMy head doesn't.\n\nPause.\n\nYASSINE:\nThat's annoying.\n\nChug almost smiles.\n\nCHUG:\nYou say that like you know yourself.\n\nYASSINE:\nMaybe I do.\nMaybe I just know what I hate."},
  {t:"[SCENE 4 — BASIC FORM]\nRaevan draws a line on the ground with his heel.\n\nRAEVAN:\nNeither of you crosses this line until I say so.\n\nCHUG:\nThat's it?\n\nRAEVAN:\nThat's enough to expose you.\n\nHe circles them.\nSlowly.\nLike he's measuring their breathing.\n\nRAEVAN:\nOne step.\nOnly one.\nTake it without warning me.\n\nChug shifts.\nRaevan taps his chest with two fingers.\nChug loses balance instantly.\n\nRAEVAN:\nLate.\n\nYassine moves next.\nHis step is smaller.\nMessier.\nBut somehow softer.\n\nRaevan's eyes narrow.\n\nRAEVAN:\nAgain.\n\nYASSINE:\nThat one was better, wasn't it?\n\nRAEVAN:\n...Again."},
  {t:"[SCENE 5 — MEMORY RESIDUE]\nYassine repeats the step.\nHe pivots oddly.\nNot textbook.\nNot clean.\nBut dangerous.\n\nRaevan blocks for real this time.\n\nCHUG:\nYou actually moved.\n\nRAEVAN:\nHe doesn't know what he's doing.\n\nYASSINE:\nThanks.\n\nRAEVAN:\nWhich makes him hard to read.\n\nGUIDE:\nResidue.\n\nCHUG:\nResidue?\n\nGUIDE:\nWhat remains when memory dies but instinct survives.\n\nYASSINE:\nSo my body is smarter than me.\n\nRAEVAN:\nFor now."},
  {t:"[SCENE 6 — FIRST PLAYABLE TEST]\nRaevan tosses a wooden short blade toward Yassine.\n\nRAEVAN:\nCatch.\n\nYassine catches it without looking.\nHe blinks.\n\nYASSINE:\n...How did I do that?\n\nGUIDE:\nYou tell us.\n\nRAEVAN tosses Chug a heavier training blade.\n\nRAEVAN:\nNow both of you.\nSpar.\n\nCHUG:\nHe's recovering.\n\nYASSINE:\nAnd you're scared I'll hit you.\n\nCHUG:\nI'm scared you'll fall apart.\n\nYASSINE:\nThen don't lose fast."},
  {t:"[SCENE 7 — SPAR ONE]\nThey circle.\nCareful.\n\nYASSINE:\nFeels weird.\n\nCHUG:\nWhat does?\n\nYASSINE:\nStanding across from you.\nLike I've done it before.\nA lot.\n\nCHUG:\n...Maybe you have.\n\nYASSINE:\nDid I win?\n\nCHUG:\nNot enough.\n\nYassine grins without knowing why.\n\nThey clash.\nQuick.\nTesting.\n\nChug goes high.\nYassine slips left.\nCounter-cuts low.\n\nRAEVAN:\nThere.\n\nGUIDE:\nHe read the shoulder.\n\nCHUG:\nHe guessed.\n\nYASSINE:\nI guessed right."},
  {t:"SYSTEM: FIGHT",fight:5},
  {t:"[SCENE 8 — HARDER]\nRaevan suddenly enters the spar.\nHe strikes both of them at once.\n\nCHUG:\nHEY—\n\nRAEVAN:\nReal fights do not wait politely.\n\nYassine ducks.\nChug blocks late.\nBoth get pushed back.\n\nRAEVAN:\nYou are both too honest.\n\nCHUG:\nYou keep calling that a flaw.\n\nRAEVAN:\nAgainst monsters, honesty is suicide."},
  {t:"[SCENE 9 — CAMP WITHOUT A CAMP]\nLater.\nThe training ground quiets.\nFragments of old pillars surround them like ruins of a forgotten dojo.\n\nYassine sits beside Chug.\nThey drink water from metal flasks Raevan left behind.\n\nYASSINE:\nSo.\n\nCHUG:\nSo.\n\nYASSINE:\nWe knew each other?\n\nCHUG:\nYeah.\n\nYASSINE:\nClose?\n\nCHUG:\n...Yeah.\n\nYASSINE:\nAnd now?\n\nCHUG:\nNow I don't know what to call this.\n\nYASSINE:\nYou can call it awkward.\n\nCHUG:\nThat works."},
  {t:"[SCENE 10 — THE ASK]\nYassine stares into the black distance.\n\nYASSINE:\nTell me something true.\n\nCHUG:\nAbout what?\n\nYASSINE:\nAbout me.\n\nLong pause.\n\nCHUG:\nYou stayed.\n\nYASSINE:\nThat all?\n\nCHUG:\nWhen things got bad.\nWhen things got weird.\nWhen I stopped looking around properly.\nYou stayed.\n\nYassine says nothing for a while.\n\nYASSINE:\n...That sounds like someone worth remembering."},
  {t:"[SCENE 11 — RAGE HINT]\nRaevan returns carrying a wrapped spear and a set of iron rings.\n\nRAEVAN:\nEnough talk.\n\nCHUG:\nWe were resting.\n\nRAEVAN:\nYou were leaking focus.\n\nHe places the iron rings in front of Chug.\n\nRAEVAN:\nPut these on your wrists.\n\nChug does.\nThey're heavier than they look.\n\nCHUG:\nWhat is this?\n\nRAEVAN:\nWeight.\nSo when power comes, you don't mistake frenzy for strength.\n\nGUIDE:\nRage control begins before Rage appears.\n\nYASSINE:\nRage?\n\nRAEVAN:\nThe thing that saves him.\nOr kills him."},
  {t:"[SCENE 12 — TARGET PRACTICE]\nRaevan plants six wooden stakes into the ground.\nDifferent distances.\nDifferent heights.\n\nRAEVAN:\nBlades are not enough.\nThe world ahead won't stay close to you.\n\nHe unwraps the spear.\n\nRAEVAN:\nThis is range.\n\nCHUG:\nI don't fight with spears.\n\nRAEVAN:\nYou don't fight with victory either.\nAnd yet you keep reaching for it.\n\nYassine snorts.\n\nYASSINE:\nI like him.\n\nCHUG:\nNo you don't.\n\nYASSINE:\nYeah.\nYou're right."},
  {t:"[SCENE 13 — THROW]\nRaevan demonstrates once.\nHe doesn't even seem to aim.\nThe spear tears through three stakes in a line.\n\nCHUG:\n...Okay.\n\nRAEVAN:\nNot okay.\nNecessary.\n\nHe hands Chug short throwing spikes.\n\nRAEVAN:\nHit the center.\n\nChug throws.\nMisses left.\n\nRAEVAN:\nYou're angry at the target.\nTargets love that.\n\nYassine throws next.\nHis spike hits wood.\nNot center.\nBut solid.\n\nYASSINE:\nI'll take it.\n\nRAEVAN:\nTake improvement instead."},
  {t:"[SCENE 14 — RANDOM CHALLENGER SEED]\nA sound breaks the training flow.\nMetal scraping stone.\n\nEveryone turns.\n\nAt the edge of the ruins stands a figure in a torn hood.\nNo face.\nNo insignia.\nA chain hangs from one hand.\n\nUNKNOWN:\nTraining already?\n\nChug steps forward.\n\nCHUG:\nWho are you?\n\nUNKNOWN:\nSomeone disappointed.\n\nYassine stands too.\nInstinctively.\n\nGUIDE:\nCareful.\n\nRAEVAN:\nBack.\nBoth of you."},
  {t:"[SCENE 15 — SHORT FIGHT]\nThe hooded challenger flicks the chain.\nIt snaps across the ground like a live wire.\n\nRAEVAN catches it with one hand.\n\nRAEVAN:\nWrong place.\n\nUNKNOWN:\nWrong era, old man.\n\nThe challenger lunges.\nFast.\nMessy.\nDesperate.\n\nChug intercepts.\nTwo strikes.\nOne block.\nOne shove.\n\nYassine pivots behind.\nDisarms with a movement he doesn't recognize.\n\nUNKNOWN stumbles back.\n\nUNKNOWN:\n...Tch.\n\nHe retreats into distortion before either can grab him."},
  {t:"SYSTEM: FIGHT",fight:6},
  {t:"[SCENE 16 — AFTER THE ENCOUNTER]\nSilence returns, but it isn't clean anymore.\n\nCHUG:\nFriend or enemy?\n\nGUIDE:\nBoth is possible.\n\nYASSINE:\nHe looked at us like he knew us.\n\nRAEVAN:\nThen assume he did.\n\nCHUG:\nWill he come back?\n\nRAEVAN:\nYes.\n\nCHUG:\nHow do you know?\n\nRAEVAN:\nBecause the weak always return with better hatred."},
  {t:"[SCENE 17 — NIGHT LESSON]\nLater.\nNo night exists here, but darkness deepens anyway.\n\nRaevan places a candle-sized blue flame between Chug and Yassine.\nIt doesn't burn the ground.\nIt only bends the air.\n\nYASSINE:\n...Magic?\n\nRAEVAN:\nA whisper of it.\nYou are not ready for more.\n\nCHUG:\nSo why show us?\n\nRAEVAN:\nBecause one day, someone will trap you in a space that answers only to their will.\n\nGUIDE:\nField.\n\nYASSINE:\nI hate that word already.\n\nRAEVAN:\nGood.\nFear makes students pay attention."},
  {t:"[SCENE 18 — CLOSING]\nChug lies awake later, staring up at a sky that isn't there.\n\nYassine is asleep two steps away, one hand still near the training blade.\n\nGUIDE:\nYou trust him.\n\nCHUG:\nI do.\n\nGUIDE:\nHe doesn't remember why.\n\nCHUG:\nI'll take what I can get.\n\nGUIDE:\nYou'll need more than trust.\n\nCHUG:\nThen I'll build more.\n\nFar away.\nSomewhere beyond the ruins.\nA heavy footstep echoes once.\n\nThen stops.\n\nSYSTEM:\n\"ALLY YASSINE — PLAYABLE STATUS UNLOCKED\""},

  {t:'[BOSS GATE — Nexter No.9 Zeph]\nThe route compresses. Everyone feels the rank pressure before the strike.\nThis is the wall for TIMING.',gl:true,col:'#d4a017'},
  {t:'SYSTEM: BOSS — NEXTER NO.9 ZEPH',fight:18},
  {t:"— END OF PART 15 —",end:true}
];
