const GROUND_OFFSET = 80;
const DEFAULT_ROUND_TIME = 50;
const BACKGROUND_PARTICLE_COUNT = 18;
const SETTINGS_STORAGE_KEY = 'chug_settings';
const DEBUG_STORAGE_KEY = 'chug_debug';
const BOSS_FIGHT_TYPES = [3,6,8,10,11,13,14,15,18,19,20];
const BEST_OF_THREE_FIGHT_TYPES = BOSS_FIGHT_TYPES;
const ENEMY_NAMES = {
  1:'VOID SHADOW',2:'RAGE CLONE',3:'FINAL ECHO',4:'SWIFT SHADOW',5:'VOID BRAWLER',
  6:'THE WATCHER',7:'LATENCY FRACTURE',8:'PREDICTION DUO',9:'ELITE MIRROR',10:'BURDEN',
  11:'CONTROLLED',12:'EVOLVED SHADOW',13:'SYNC WAVE',14:'REWRITE PROTOCOL',15:'MEMORY ERASURE',
  16:'INTERFERENCE WAVE',17:'PRESSURE WAVE',18:'THE DELAY',19:'FINAL INTERFERENCE',20:'FINAL HOST'
};
